# Generated by Django 4.1 on 2024-05-15 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0001_initial"),
        ("contacts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenant.tenant",
            ),
            preserve_default=False,
        ),
    ]
