# Generated by Django 4.1 on 2024-08-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_temps', '0002_initial'),
        ('contacts', '0004_remove_contact_first_name_remove_contact_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='node_temps.nodetemplate'),
        ),
    ]
