# Generated by Django 4.1 on 2024-08-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_flow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='flow',
        ),
    ]
