# Generated by Django 4.1 on 2024-08-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
