# Generated by Django 4.1 on 2024-08-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

   

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='createdBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
