# Generated by Django 4.2.1 on 2024-04-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="money",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Money",
            ),
        ),
    ]
