# Generated by Django 4.1 on 2024-08-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0002_wa"),
<<<<<<< HEAD
=======
       
>>>>>>> ad1da1cdca1c8ccc18ee33877c1227834c8d96aa
    ]

