# Generated by Django 4.1 on 2024-06-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("in process", "In Process"),
                    ("converted", "Converted"),
                    ("recycled", "Recycled"),
                    ("dead", "Dead"),
                ],
                default="assigned",
                max_length=255,
                verbose_name="Status of Lead",
            ),
            preserve_default=False,
        ),
    ]
