# Generated by Django 4.1 on 2024-08-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_wa'),
        ('leads', '0002_remove_report_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
    ]
