# Generated by Django 4.1 on 2024-08-27 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0002_wa"),
       
    ]

   