# Generated by Django 4.2.1 on 2024-05-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaign_owner", models.CharField(max_length=255)),
                ("campaign_name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "expected_revenue",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("actual_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("numbers_sent", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("None", "None"), ("Email", "Email"), ("SMS", "SMS")],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Active", "Active"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("budgeted_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "expected_response",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
