# Generated by Django 4.1 on 2024-08-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_campaign_type_whatsappcampaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='email_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
