# Generated by Django 4.1 on 2024-07-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0001_initial"),
        ("whatsapp_chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="source",
            field=models.CharField(default="whatsapp", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversation",
            name="tenant",
            field=models.ForeignKey(
                default="ll",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenant.tenant",
            ),
            preserve_default=False,
        ),
    ]
