# Generated by Django 4.1 on 2024-08-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_chat', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
