# Generated by Django 2.0.5 on 2018-05-04 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='calls',
            fields=[
                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Related To')),
                ('call_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Call Type')),
                ('outgoing_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outgoing Status')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('call_duration', models.DurationField(blank=True, null=True, verbose_name='Call Duration')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('voice_recording', models.CharField(blank=True, max_length=255, null=True, verbose_name='Voice Recording')),
                ('to_time', models.DateTimeField(blank=True, null=True, verbose_name='To')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_calls', to=settings.AUTH_USER_MODEL)),
                ('call_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_to_meetings', to='contacts.Contact', verbose_name='Contact Name')),
            ],
        ),
    ]