# Generated by Django 4.2.1 on 2024-05-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="calls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "related_to",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Related To"
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Call Type"
                    ),
                ),
                (
                    "outgoing_status",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Outgoing Status",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start Time"
                    ),
                ),
                (
                    "call_duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Call Duration"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Location"
                    ),
                ),
                (
                    "voice_recording",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Voice Recording",
                    ),
                ),
                (
                    "to_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="To"),
                ),
            ],
        ),
    ]
