# Generated by Django 4.2.1 on 2024-04-09 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("calls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calls",
            name="call_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="call_to_meetings",
                to="contacts.contact",
                verbose_name="Contact Name",
            ),
        ),
        migrations.AddField(
            model_name="calls",
            name="createdBy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_calls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
