# Generated by Django 4.2.1 on 2024-05-15 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("calls", "0001_initial"),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calls",
            name="call_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="call_to_meetings",
                to="contacts.contact",
                verbose_name="Contact Name",
            ),
        ),
    ]
