# Generated by Django 4.1 on 2024-08-10 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_initial"),
        ("campaign", "0003_alter_campaign_type_whatsappcampaign_and_more"),
        ("calls", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("Outbound", "Outbound"),
                            ("Inbound", "Inbound"),
                            ("Follow-Up", "Follow-Up"),
                            ("Survey", "Survey"),
                            ("Sales", "Sales"),
                        ],
                        default="Outbound",
                        max_length=50,
                    ),
                ),
                ("call_script", models.TextField(blank=True, null=True)),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "expected_response_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "actual_response_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_campaigns",
                        to="campaign.campaign",
                    ),
                ),
                (
                    "contacts",
                    models.ManyToManyField(
                        blank=True, related_name="call_campaigns", to="contacts.contact"
                    ),
                ),
            ],
            options={
                "unique_together": {("campaign", "campaign_type")},
            },
        ),
    ]
