# Generated by Django 4.1 on 2024-06-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_owner", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=100)),
                ("product_code", models.CharField(max_length=50, unique=True)),
                ("vendor_name", models.CharField(max_length=100)),
                ("product_active", models.BooleanField(default=True)),
                ("manufacturer", models.CharField(max_length=100)),
                ("product_category", models.CharField(max_length=100)),
                ("sales_start_date", models.DateField(blank=True, null=True)),
                ("sales_end_date", models.DateField(blank=True, null=True)),
                ("support_start_date", models.DateField(blank=True, null=True)),
                ("support_end_date", models.DateField(blank=True, null=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("tax", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_taxable", models.BooleanField(default=False)),
                ("usage_unit", models.CharField(max_length=50)),
                ("qty_ordered", models.PositiveIntegerField(default=0)),
                ("reorder_level", models.PositiveIntegerField(default=0)),
                ("quantity_in_stock", models.PositiveIntegerField(default=0)),
                ("handler", models.CharField(max_length=100)),
                ("quantity_in_demand", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenant.tenant"
                    ),
                ),
            ],
        ),
    ]
