# Generated by Django 4.1 on 2024-08-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_custom_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='custom_fields',
            new_name='custom_field',
        ),
    ]
