# Generated by Django 4.1 on 2024-08-13 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_custom_field_product_custom_field_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='custom_field_id',
            new_name='custom_field',
        ),
    ]
