# Generated by Django 4.1 on 2024-08-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_custom_field_id_product_custom_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_field',
        ),
    ]
