# Generated by Django 4.1 on 2024-08-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_custom_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
