# Generated by Django 4.1 on 2024-08-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_vendor_name_product_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
