# Generated by Django 4.1 on 2024-08-21 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('product', '0009_alter_product_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_name', models.CharField(max_length=200)),
                ('highlights', models.TextField()),
                ('slot_timing', models.CharField(max_length=100)),
                ('sale_price', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('duration_in_hours', models.IntegerField()),
                ('itenerary', models.TextField()),
                ('itenerary_time', models.CharField(max_length=50)),
                ('inclusions_and_exclusions', models.TextField()),
                ('additional_information', models.CharField(max_length=255)),
                ('time_of_the_day', models.CharField(max_length=50)),
                ('experience', models.TextField()),
                ('eligibility', models.CharField(max_length=100)),
                ('proibitions_and_limitations', models.TextField()),
                ('what_to_bring', models.TextField()),
                ('terms_and_cancellations', models.TextField()),
                ('insider_tip', models.TextField()),
                ('description', models.TextField()),
                ('vendor_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendors')),
            ],
        ),
    ]
