# Generated by Django 4.1 on 2024-08-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_unit_price_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='itenerary_time',
            field=models.TextField(),
        ),
    ]
