# Generated by Django 4.1 on 2024-08-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_experience_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='vendor_owner',
            field=models.CharField(max_length=255),
        ),
    ]
