# Generated by Django 4.1 on 2024-08-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_experience_vendor_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='additional_information',
            field=models.TextField(),
        ),
    ]
