# Generated by Django 4.1 on 2024-08-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_experience_additional_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='eligibility',
            field=models.CharField(max_length=200),
        ),
    ]
