# Generated by Django 4.1 on 2024-08-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_experience_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='slot_timing',
            field=models.CharField(max_length=200),
        ),
    ]
