# Generated by Django 4.1 on 2024-08-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_experience_duration_in_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='duration_in_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
