# Generated by Django 4.1 on 2024-08-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_experience_duration_in_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='additional_information',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='eligibility',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='highlights',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='inclusions_and_exclusions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='insider_tip',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='itenerary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='itenerary_time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='proibitions_and_limitations',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='sale_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='slot_timing',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='tax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='terms_and_cancellations',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='time_of_the_day',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='vendor_owner',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='what_to_bring',
            field=models.TextField(null=True),
        ),
    ]
