# Generated by Django 4.1 on 2024-08-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_experience_duration_in_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='sale_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='tax',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
