# Generated by Django 4.1 on 2024-08-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_experience_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='sale_price',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
