# Generated by Django 4.1 on 2024-08-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_unit_price'),
        ('product', '0023_alter_experience_sale_price'),
    ]

    operations = [
    ]
