# Generated by Django 4.1 on 2024-08-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_merge_20240822_1458'),
        ('product', '0024_merge_20240822_1824'),
    ]

    operations = [
    ]
