# Generated by Django 4.1 on 2024-08-27 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_merge_20240824_1424'),
        ('product', '0025_merge_20240826_1649'),
    ]

    operations = [
    ]
