# Generated by Django 4.1 on 2024-09-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_merge_20240827_0942'),
        ('product', '0026_merge_20240827_1418'),
    ]

    operations = [
    ]
