# Generated by Django 4.1 on 2024-08-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cltv',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.customer'),
        ),
    ]
