# Generated by Django 4.2.1 on 2024-05-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("db_user", models.CharField(max_length=100)),
                ("db_user_password", models.CharField(max_length=100)),
            ],
        ),
    ]
