# Generated by Django 4.1 on 2024-05-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="organization",
            field=models.CharField(default="nuren", max_length=100),
            preserve_default=False,
        ),
    ]
