# Generated by Django 4.1 on 2024-08-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_temps', '0003_flow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flow',
            old_name='adjList',
            new_name='adj_list',
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='currNode',
            new_name='curr_node',
        ),
    ]
