# Generated by Django 4.2.1 on 2024-04-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_id", models.PositiveIntegerField()),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("Call", "Call"),
                            ("Email", "Email"),
                            ("Meeting", "Meeting"),
                            ("Note", "Note"),
                        ],
                        max_length=50,
                    ),
                ),
                ("interaction_datetime", models.DateTimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
