# Generated by Django 4.1 on 2024-09-06 06:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0006_remove_contact_flow'),
        ('tenant', '0002_wa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('time_open', models.DateTimeField(blank=True, null=True)),
                ('tracking_id', models.CharField(max_length=255, unique=True)),
                ('operator', models.CharField(blank=True, choices=[('hostinger', 'Hostinger'), ('email', 'Email'), ('zoho', 'Zoho'), ('outlook', 'Outlook'), ('other', 'Other')], max_length=20, null=True)),
                ('time', models.DateTimeField()),
                ('subject', models.CharField(max_length=255)),
                ('email_type', models.CharField(blank=True, choices=[('draft', 'Draft'), ('sent', 'Sent')], max_length=5, null=True)),
                ('email_id', models.EmailField(max_length=255)),
                ('links', models.JSONField(default=list)),
                ('email_html', models.TextField(blank=True, null=True)),
                ('open_count', models.IntegerField(default=0)),
                ('total_time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('attachments', models.JSONField(default=list)),
                ('last_open_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Title')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('from_time', models.DateTimeField(verbose_name='From')),
                ('to_time', models.DateTimeField(verbose_name='To')),
                ('related_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Related To')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.account')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_assigned_users', to=settings.AUTH_USER_MODEL)),
                ('contact_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_contacts', to='contacts.contact', verbose_name='Contact Name')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_created_by', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_hosts', to=settings.AUTH_USER_MODEL, verbose_name='Host')),
                ('participants', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participants', to='contacts.contact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.PositiveIntegerField()),
                ('interaction_type', models.CharField(choices=[('Call', 'Call'), ('Email', 'Email'), ('Meeting', 'Meeting'), ('Note', 'Note')], max_length=50)),
                ('interaction_datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='groups', to='contacts.contact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=255)),
                ('message_text', models.TextField()),
                ('sender', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Related To')),
                ('call_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Call Type')),
                ('outgoing_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outgoing Status')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('call_duration', models.DurationField(blank=True, null=True, verbose_name='Call Duration')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('voice_recording', models.CharField(blank=True, max_length=255, null=True, verbose_name='Voice Recording')),
                ('to_time', models.DateTimeField(blank=True, null=True, verbose_name='To')),
                ('call_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_to_meetings', to='contacts.contact', verbose_name='Contact Name')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_calls', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
    ]
