# Generated by Django 4.1 on 2024-08-07 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0002_initial'),
        ('tenant', '0001_initial'),
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Related To')),
                ('call_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Call Type')),
                ('outgoing_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outgoing Status')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('call_duration', models.DurationField(blank=True, null=True, verbose_name='Call Duration')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('voice_recording', models.CharField(blank=True, max_length=255, null=True, verbose_name='Voice Recording')),
                ('to_time', models.DateTimeField(blank=True, null=True, verbose_name='To')),
                ('call_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_to_meetings', to='contacts.contact', verbose_name='Contact Name')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_calls', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
    ]
