# Generated by Django 4.1 on 2024-08-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0004_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('time_open', models.DateTimeField()),
                ('tracking_id', models.CharField(max_length=255, unique=True)),
                ('operator', models.CharField(blank=True, choices=[('hostinger', 'Hostinger'), ('email', 'Email'), ('zoho', 'Zoho'), ('outlook', 'Outlook'), ('other', 'Other')], max_length=20, null=True)),
                ('time', models.DateTimeField()),
                ('subject', models.CharField(max_length=255)),
                ('email_type', models.CharField(blank=True, choices=[('draft', 'Draft'), ('sent', 'Sent')], max_length=5, null=True)),
            ],
        ),
    ]
