# Generated by Django 4.1 on 2024-08-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0006_alter_email_time_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_id',
            field=models.EmailField(default='testing@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
