# Generated by Django 4.1 on 2024-08-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interaction", "0007_email_email_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="links",
            field=models.JSONField(default=list),
        ),
    ]
