# Generated by Django 4.1 on 2024-08-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0008_email_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
