# Generated by Django 4.1 on 2024-08-26 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0009_email_email_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='open_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='total_time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
