# Generated by Django 4.1 on 2024-08-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0010_email_open_count_email_total_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='attachments',
            field=models.JSONField(default=list),
        ),
    ]
