# Generated by Django 4.1 on 2024-08-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0009_email_open_times_email_total_time_spent_group'),
        ('interaction', '0011_email_attachments'),
    ]

    operations = [
    ]
