# Generated by Django 4.1 on 2024-08-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0012_merge_20240827_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='open_times',
        ),
    ]
