# Generated by Django 4.1 on 2024-08-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0013_remove_email_open_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='last_open_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
