# Generated by Django 4.2.1 on 2024-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Name",
                    models.CharField(max_length=64, verbose_name="Name of Account"),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FINANCE", "FINANCE"),
                            ("HEALTHCARE", "HEALTHCARE"),
                            ("INSURANCE", "INSURANCE"),
                            ("LEGAL", "LEGAL"),
                            ("MANUFACTURING", "MANUFACTURING"),
                            ("PUBLISHING", "PUBLISHING"),
                            ("REAL ESTATE", "REAL ESTATE"),
                            ("SOFTWARE", "SOFTWARE"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Industry Type",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "createdOn",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created on"),
                ),
                ("isActive", models.BooleanField(default=False)),
                ("company", models.CharField(default="Unknown", max_length=100)),
            ],
        ),
    ]
