# Generated by Django 4.1 on 2024-05-16 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_account_tenant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="account",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_assigned_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
