# Generated by Django 4.1 on 2024-06-06 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynamic_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmodel',
            name='created_by',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
