# Generated by Django 4.1 on 2024-06-12 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenant", "0001_initial"),
        ("dynamic_entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicfield",
            name="dynamic_model",
            field=models.ForeignKey(
                default="3",
                on_delete=django.db.models.deletion.CASCADE,
                to="dynamic_entities.dynamicmodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dynamicmodel",
            name="created_by",
            field=models.ForeignKey(
                default="7",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dynamicmodel",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenant.tenant",
            ),
        ),
    ]
