# Generated by Django 4.1 on 2024-05-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
        migrations.AddField(
            model_name="document",
            name="file_url",
            field=models.URLField(default="", verbose_name="File URL"),
        ),
    ]
