# Generated by Django 4.1 on 2024-06-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(max_length=600, verbose_name="Document Type"),
        ),
        migrations.AlterField(
            model_name="document",
            name="entity_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="entity_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_url",
            field=models.CharField(default="", max_length=600, verbose_name="File URL"),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(max_length=600, verbose_name="Document Name"),
        ),
    ]
