# Generated by Django 4.1 on 2024-05-31 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0002_tenant_organization"),
        ("documents", "0002_remove_document_file_document_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="tenant",
            field=models.ForeignKey(
                default="3",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenant.tenant",
            ),
            preserve_default=False,
        ),
    ]
