# Generated by Django 4.1 on 2024-08-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0003_message_platform_message_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="messages",
            field=models.TextField(default="Empty"),
            preserve_default=False,
        ),
    ]
