# Generated by Django 4.1 on 2024-08-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0004_conversation_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="mapped",
            field=models.BooleanField(default=False),
        ),
    ]
