# Generated by Django 4.1 on 2024-08-31 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_message_mapped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentimentanalysis',
            old_name='message_id',
            new_name='conversation_id',
        ),
    ]
