# Generated by Django 4.1 on 2024-09-02 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contact_first_name_remove_contact_last_name_and_more'),
        ('communication', '0006_rename_message_id_sentimentanalysis_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='contact_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
            preserve_default=False,
        ),
    ]
