# Generated by Django 4.1 on 2024-09-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_sentimentanalysis_contact_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='contact_id',
        ),
    ]
