# Generated by Django 4.1 on 2024-09-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_remove_contact_flow'),
        ('topicmodelling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodelling',
            name='contact_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='topic_modelling_contacts', to='contacts.contact'),
            preserve_default=False,
        ),
    ]
