# Generated by Django 4.1 on 2024-06-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customfield',
            old_name='name',
            new_name='custom_field',
        ),
    ]
