# Generated by Django 4.1 on 2024-08-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('custom_fields', '0002_remove_customfield_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
    ]
