# Generated by Django 4.1 on 2024-08-13 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_custom_field_product_custom_field_id'),
        ('custom_fields', '0003_alter_customfield_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_set', to='product.product'),
        ),
    ]
