# Generated by Django 4.1 on 2024-08-13 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('custom_fields', '0003_alter_customfield_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='entity_id',
        ),
        migrations.AddField(
            model_name='customfield',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
