# Generated by Django 4.1 on 2024-08-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0005_alter_customfield_content_type_and_more'),
        ('custom_fields', '0005_remove_customfield_product'),
    ]

    operations = [
    ]
