# Generated by Django 4.1 on 2024-07-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drafts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drafts",
            name="image_url",
            field=models.JSONField(),
        ),
    ]
